### PR TITLE
Proper auth, simplify defaulttemplate vs per template

### PR DESCRIPTION
**Pull request by elbuo8**

### CODE REVIEW

**Comment by elbuo8** [comment]
* The options object should take in an Auth object where credentials are stored.

* Simplify templates by having the same key. Overrides can still happen on a per-email basis.

**Comment by devinus** [comment]
Unsure. It's actually not standard to use an `auth` object, only the SMTP and SendGrid transport uses it. For example, another API transport, the official Amazon SES transport (https://github.com/andris9/nodemailer-ses-transport) doesn't.

Also `defaultTemplate` is clearer than just `template`. It's implied that it's overridable when calling `sendMail`.

I don't really care that much, though, but it should be functionally equivalent. For example, it allows an empty apiKey/apiSecret right now, in which case you'll get a nice error from the Sailthru client.

**Comment by elbuo8** [comment]
Pull request will also blow up if keys don't exist in auth object. 

Given that the default transports use the auth object, I'd say nodemailer itself pushes that to the standard. (SMTP is part of core)

**Comment by elbuo8** [comment]
Sorry, services are part of core. And that uses the auth block.

Plus SMTP.

**Comment by motdotla** [comment]
For my thoughts:

+ I like the use of defaultTemplate here - especially since you can override template [1] 
+ I personally prefer the mechanism of the auth object. I like it's pattern and added readability.

[1] https://github.com/RebelMail/nodemailer-sailthru-transport/blob/master/lib/sailthru-transport.js#L20

**Comment by elbuo8** [comment]
@motdotla the PR allows you to override the `defaultTemplate` also.

You instantiate your transport with `template` making it the default one. On a per email basis, you can pass `template` and it will override the default one for that given email. Same functionality, just simplified by having just 1 key.

**Comment by motdotla** [comment]
This is related to this: https://github.com/RebelMail/nodemailer-sailthru-transport/issues/2

Closing that relation, and just having this live here.

**What should we settle on for this?** 

I am personally a fan of using the `auth` approach - some of that is personal preference and some of that is contentment with running tests on QA through the smtp transport.

**Comment by elbuo8** [comment]
Regardless of what we do, we will have to create a factory in order to keep adding Transports so it works with those which don't use `auth` block etc. But +1 for `auth` block.

For the keys, I still vouch for a single one.

**Pull request merged**
